[package]
name = "pizza-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.49", features = ["derive"] }
comfy-table = "7.2.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
pizza-core = { path = "../pizza-core" }