name: Release Pipeline

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test-and-lint:
    name: Test & Lint (Clippy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Tests
        run: cargo test --workspace --all-features --all

  release-please:
    name: Release Please (Conventional Commits)
    runs-on: ubuntu-latest
    needs: test-and-lint
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .github/release-please-manifest.json

  build-and-upload:
    name: Build & Upload Binaries
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
            archive: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
            archive: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
            archive: zip
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build (pizza-cli)
        working-directory: pizza-cli
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Package artifact
        shell: bash
        run: |
          set -euo pipefail
          BIN_NAME="pizza-cli${{ matrix.ext }}"
          TAG="${{ needs.release-please.outputs.tag_name }}"
          OUT_DIR="dist"
          mkdir -p "$OUT_DIR"

          BIN_PATH="target/${{ matrix.target }}/release/${BIN_NAME}"

          # Compose archive name
          ARCHIVE="pizza-cli-${TAG}-${{ matrix.target }}.${{ matrix.archive }}"

          if [ "${{ matrix.archive }}" = "zip" ]; then
            7z a "$OUT_DIR/$ARCHIVE" "$BIN_PATH"
          else
            tar -C "target/${{ matrix.target }}/release" -czf "$OUT_DIR/$ARCHIVE" "$BIN_NAME"
          fi

          echo "ARCHIVE_PATH=$OUT_DIR/$ARCHIVE" >> $GITHUB_ENV

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release-please.outputs.tag_name }}
          files: ${{ env.ARCHIVE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
